# Solutions? 

## Mechanical Cooling 
:::: {.columns}

::: {.column width="50%"}
**Pros**

- Easy to design for 
- Accepted in industry 
- Enabled increased productivity 
- Reliable
:::



::: {.column width="50%" .fragment .incremental}
**Cons** 

- Susceptible to failure during heat waves 

  ::: {.smaller}
  - Loads increase when power system most vulnerable, leading to blackouts 
  - In Shanghai, documented shortages greater than a 1 GWh ^[@liangHeatWaveElectricity2016]
  :::

- Energy intensive 

  ::: {.smaller}
  - AC + electric fan account for 20% of total energy use in buildings ^[@internationalenergyagencyFutureCoolingOpportunities2018]
  :::

- Inaccesible 

  ::: {.smaller}
  - Ability to own an AC constrained by income ^[@internationalenergyagencyFutureCoolingOpportunities2018]
    - 99% of private apartments in Singapore have AC
    - Closer to 4% of households in India 
  :::
:::

::::

## Viscous Cycle 
<!-- TODO figure of visous cycle  -->


## Natural Cooling 
:::: {.columns}

::: {.column width="50%"}
**Pros**

- Low operational energy 
- Accessible 
- Has worked well for some time 

  ::: {.smaller}
  - Modern AC unit invented in 1900 and only became popular in the US in the 1950s ^[@internationalenergyagencyFutureCoolingOpportunities2018]
  :::
:::

::: {.column width="50%" .fragment}
**Cons**

- Difficult to design for 
- Industry skepticism 
- Unreliable due to uncertainty 
  - Occupant behavior 
  - Outdoor climate 

:::

::::


## Cooling "Tech"
<!-- TODO zhang figure -->

::: aside
@zhangResilientCoolingStrategies2021a
:::

---
"Vernacular building traditions across the world display ... sophisticated thermal adaptation" - Lisa Heschong, Thermal Delight in Architecture 
<!-- TODO zhang figure + lisa interventions  -->

::: aside
@heschongThermalDelightArchitecture1979
:::
<!-- TODO repeat and circle ventilation   -->


## Why Windows?
:::: {.columns }



::: {.column width="50%"}

:::{.styled-side}
  *Climate and occupant uncertainty*
:::

:::


::: {.column width="50%"}

:::{.incremental}

  - What is the effect of window opening and closing on indoor climate?
  - How does this change with different building designs, occupant behavior, and outdoor climate?
  - How can practitioners access and leverage this information in the early stages of the design process? 

:::

:::

::::

## Why Predicting W/O/C is Useful
- uninvasive way of determining if windows open/closed 
- can enable better understanding of occupant behavior 
- understanding when windows are open, enables us to use to contextual information understand why they are open
  - D'Oca and Hong grouped occupants into 3-types: thermal-driven, time-driven, thermal+time driven ^[@docaDataminingApproachDiscover2014]
- critical information for designers 

## W/O/C Predictions since 1990...
<!-- TODO timeline   -->
  - Dai 2020 Table 1 => popular methods + Fig 5 => frequency of ML methods used, 4.2.1 = prediction of window opening closing action 
    - fritsch, 1990 [54] Markov chain methods 
    - Haldi and Robinson [78] markov chain + logistic regression 
    - Schweiker [79] tested this (also the source of external data!) => differences in culture meant different performance 
    - Markovic [80] Bayesian and random forest 
    - de rautlin de roy, 2023, looked at different learning techniques 


::: aside
@docaDataminingApproachDiscover2014
:::

## Research Gaps 
<!-- TODO table with author, length of data collected, location, method, and supervised/not    -->
  - gaps:  
    - long data collection periods: shorter periods are needed for practical use
    - only supervised models : unclear how coefficients/models transfer to radically different buildings in different climates


::: aside
discussion of supervised vs not.
::: 