# Abstract 

Natural cooling, utilizing non-mechanical cooling, presents a low-carbon and low-cost way to provide thermal comfort in residential buildings. However, naturally cooled residential buildings are difficult to design without a clear understanding of the effect opening and closing windows will have on occupant thermal comfort. Predicting when and understanding why occupants open windows is a difficult task in itself. Although work has been done on creating predictive window opening and closing models, they traditionally rely on large datasets, specialized sensing, and/or require training data for each building. This makes them ineffective tools for scaling natural cooling to a large number of buildings. Here, we propose a novel unsupervised window opening and closing detection method that utilizes easy-to-deploy off-the-shelf temperature and humidity sensors. We assess our proposed models' effectiveness on an empirical dataset. We also compare the method's performance with a support vector machine (SVM) model that represents the state-of-the-art in window detection. We find that the proposed method outperformed the SVM on a number of key indicators, but had subpar performance on data in which the indoor and outdoor temperature had small differences. While the SVM's performance was sensitive to the characteristics of the time series features, our proposed method, which relies on indoor temperature alone, demonstrated robust performance in our pilot studies, making it a potential candidate for developing a highly scalable and generalizable model for window operation detection. Overall, this work aims to demonstrate the viability of using unsupervised data-driven methods for understanding window operations in residential buildings. In doing so, we aim to enable more accurate modeling of naturally cooled buildings and further catalyze widespread adoption of this low-cost and low-carbon technology.



