# Conclusions and Future Work 

We presented preliminary results showcasing the efficacy of a new method, ST, for unsupervised window detection. We compared these results with SVM models trained with optimized features, and found comprable results. Using datasets with notable differences in window state balance and contrast between indoor and outdoor temperatures enabled us to begin to test the limits of this new method. 

Analyzing a standard metric, the F1-score, as well as the several window detection specic metrics enabled us to develop a more nuanced understanding of the nature of the predictions the models made. The highest performing SVMs for example, tended to detect signifantly more change points than actually occured in the data. While this behavior can lead to higher accuracy, it can be harmful for unsupervised detection. For designing naturally cooled buildings particularly, a practictioner might want to infer a user's likelihood to use operable windows to regulate their thermal comfort. The predictions from the SVM models would suggest that, since windows are frequently being opened or closed, users are highly engaged with temperature manipulation, when in reality this is not the case. Therefore, understanding why window detection is needed, and then creating metrics that respond to this specific use-case is a key step of unsupervised window state detection.

## Future Work 
Although ST has shown promising results, we believe that there are a number of steps that can be explored for improving its performance. First, our method does not take into account the material properties of the room where data is being collected, although this data would be available from construction documentation. This information could help to simulate response of indoor quantities of interest to daily seasonal changes in ambient quantities using simple heat transfer equations. This would enable us to more precisely identify the seasonal component in indoor time series which would be an immprovement from the simple smoothing technique we use here. The addition of momentum equations to our simulation would enable us examine the magnitude of temperature change that connvective heat transfer permits when a window is open vs closed. Understanding expected indoor temperature changes under different conditions would help to make more educated guesses in the guessing step of the ST.  In summary, augmenting the current data-driven ST with a better underestanding of the physical processes underlying the data is a critical next step.

The ST could also possibly be improved carrying out a similar process for relative humidity as temperature. Features involving relative humidity featured heavily in the top-performing SVMs, which makes sense, as indoor relative humidity does have some correlation to ambient properties. Similar physical simulations as described above could be carried out to better understand this relationship. 

Spatial simulations and measurements could also be helpful in determining where a sensor should be placed in a room to best capture the fluctuations in quantities of interest. For this simulation, sensors were intentionally placed away from from windows so as avoid drafts and better capture the average temperaure of a space. However, it is conceivable that sensors placed closer to a window would be more sensitive to changes in the window state, and thus record a stronger window change detection signal. 

Finally, future work should involve evaluating this method on a wider variety of datasets. Although the datasets presented here do have significant differences, they were all collected in adjacent rooms in the same building. Changing the location where data is collected, and exploring further ranges of balanced datasets and indoor-outdoor temperature relationships will be key for validating an unsupervised model.